name: Deploy Express to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Copier tous les fichiers sur le VPS
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/TP-API/Express"
          strip_components: 1
          rm: false

      # Installer les dépendances directement sur le VPS et redémarrer l'app
      - name: SSH, install deps and restart app
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/TP-API/Express
            rm -rf node_modules package-lock.json       # Nettoyer complètement
            npm install                                 # Installer sur Linux
            pm2 restart mon-express || pm2 start app.js --name mon-express
